---
- hosts: webserver
  remote_user: root
  become: yes
  vars_prompt:
    - name: pkg
      prompt: enter package name
      private: no

  tasks:
    - name: install
      yum: name={{pkg}} state=installed
    - name: copy index.html file
      copy: src=index.html dest=/var/www/html
    - name: start syed
      service: name={{pkg}} state=started
